CREATE TABLE IF NOT EXISTS `preinscripcion` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `idusuario` varchar(50) NOT NULL,
  `nombre` varchar(255) NOT NULL,
  `username` varchar(255) NOT NULL,
  `email` varchar(255) DEFAULT NULL,
  `tlf` varchar(50) DEFAULT NULL,
  `cel` varchar(50) DEFAULT NULL,
  `direccion` text,
  `ciudad` varchar(100) DEFAULT NULL,
  `estado` varchar(100) DEFAULT NULL,
  `municipio` varchar(100) DEFAULT NULL,
  `parroquia` varchar(100) DEFAULT NULL,
  `etnia` varchar(100) DEFAULT NULL,
  `casaapto` varchar(255) DEFAULT NULL,
  `punto_referencia` varchar(255) DEFAULT NULL,
  `grupo_familiar` int DEFAULT 0,
  `acargo_usted` int DEFAULT 0,
  `fuente_ingresos` varchar(255) DEFAULT NULL,
  `tipo_vivienda` varchar(100) DEFAULT NULL,
  `tenencia_vivienda` varchar(100) DEFAULT NULL,
  `enfermedad` text,
  `discapacidad` varchar(255) DEFAULT NULL,
  `titulos` text,
  `institutos` text,
  `potencialidades` text,
  `carrera` int DEFAULT NULL,
  `genero` varchar(50) DEFAULT NULL,
  `edo_civil` varchar(100) DEFAULT NULL,
  `fecha_nac` date DEFAULT NULL,
  `embarazada` varchar(10) DEFAULT NULL,
  `num_telf_opc` varchar(50) DEFAULT NULL,
  `fecha_ingreso` date DEFAULT NULL,
  `fecha_act` datetime DEFAULT NULL,
  `status` varchar(50) DEFAULT 'Pendiente',
  `user_type` varchar(50) DEFAULT 'preinscrito',
  `foto_perfil` varchar(255) DEFAULT NULL,
  `aprobado_por` int DEFAULT NULL,
  `fecha_aprobado` datetime DEFAULT NULL,
  `rechazado_por` int DEFAULT NULL,
  `fecha_rechazo` datetime DEFAULT NULL,
  `motivo_rechazo` text,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_idusuario` (`idusuario`),
  UNIQUE KEY `idx_username` (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
